version: '3'

services:
    app:
        build: ./app/
        volumes:
            - ./app/logs:/var/log/nginx
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./db/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: foo
            POSTGRES_PASSWORD: foobar
            POSTGRES_DB: baz
# volumes:
#    db-data: